server:
    address: 0.0.0.0
    port: 8080
spring:
    application:
        name: tamilSchool
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:file:C:\Users\gkeer\Downloads\tamilSchool\tamilSchool
       # url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: update

